# at v0.6.0
disabled_rules:
  - function_body_length
  - type_body_length
  - identifier_name
  - cyclomatic_complexity

file_length:
  warning: 500
identifier_name:
  max_length:
    warning: 45
    error: 60
  min_length:
    warning: 0
